# Generated by Django 5.2.11 on 2026-02-08 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ai_checked', models.BooleanField(default=False)),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
            options={
                'ordering': ['created_date'],
                'indexes': [models.Index(fields=['post', 'created_date'], name='comments_co_post_id_d88bb8_idx'), models.Index(fields=['parent'], name='comments_co_parent__fdf1ec_idx'), models.Index(fields=['is_visible'], name='comments_co_is_visi_6176cd_idx')],
            },
        ),
    ]
